### ISSUE TITLE
Can't run the app after installing okrand

### ISSUE THREAD

**Issue by etamponi** [boxed/okrand#1]
This is the error I get when I run `python manage.py runserver` or any other `manage.py` command:

```
Traceback (most recent call last):
  File "/home/emanuele/django/dev/hh/manage.py", line 22, in <module>
    main()
  File "/home/emanuele/django/dev/hh/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/okrand/apps.py", line 48, in ready
    upgrade_verbose_name(model._meta)
  File "/home/emanuele/django/dev/hh/.venv/lib/python3.12/site-packages/okrand/apps.py", line 14, in upgrade_verbose_name
    obj.verbose_name._okrand_original_string = original._proxy____args[0]
                                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '__proxy__' object has no attribute '_proxy____args'. Did you mean: '_proxy____cast'?
```

**Comment by etamponi** [comment]
5.1

**Comment by etamponi** [comment]
It seems related to an admin.logentry object.

**Comment by boxed** [comment]
hmm. it seems I had this turned off on my work project, that's unfortunate. 

It was indeed broken in Django 5! I released version 1.1.1 that fixes this.

**Comment by etamponi** [comment]
Should I also add iommi.admin.Admin to my urls? Or is i18n enough? Also I think you should add `iommi` to the requirements of the package, otherwise `pip install okrand` won't install iommi.

**Comment by etamponi** [comment]
I am still not sure how to use this... I added iommi.admin.Admin().urls() to my urlpattern, as well as okrand.views.i18n... but I get 404s when I try to navigate to those pages.

EDIT: oh, I need to be a superuser... perhaps a 404 is not the best way to handle this :)

**Comment by boxed** [comment]
I don't think I should force users to install iommi to get the nice UI page. That's a nice-to-have, not a requirement.

As for the 404, well.. that's me being paranoid about security from having worked in banking. We were very careful not to make it possible to find out stuff from getting a 403 on a certain url :P Maybe that's wrong in this case...

Hmm. I guess it crashes on an `{% include %}` tag? Seems weird. I have those in my project and it doesn't crash for me. Looking at InclusionNode it looks broken in Django actually. It shouldn't specify `nodelist` as a child node list, as it has none. 

If you change `nodelist = getattr(node, child_nodelist)` to `nodelist = getattr(node, child_nodelist, [])` does it start to work?

**Comment by etamponi** [comment]
I just get a new error:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/i18n/

Django Version: 5.1.1
Python Version: 3.12.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_bootstrap5',
 'django_select2',
 'allauth',
 'allauth.account',
 'iommi',
 'okrand',
 'pwa',
 'handover.apps.HandoverConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'allauth.account.middleware.AccountMiddleware',
 'handover.middleware.TimezoneMiddleware',
 'handover.middleware.current_user_middleware',
 'handover.middleware.current_ward_middleware',
 'handover.middleware.time_travel_middleware']



Traceback (most recent call last):
  File "/home/emanuele/.cache/pypoetry/virtualenvs/hh-pqyorWhg-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emanuele/.cache/pypoetry/virtualenvs/hh-pqyorWhg-py3.12/lib/python3.12/site-packages/allauth/account/middleware.py", line 43, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emanuele/.cache/pypoetry/virtualenvs/hh-pqyorWhg-py3.12/lib/python3.12/site-packages/allauth/account/middleware.py", line 121, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /i18n/
Exception Value: 'Page' object has no attribute 'status_code'
```

**Comment by etamponi** [comment]
If I try to fix the previous error with a getattr(...), a new one shows up, and so on...

**Comment by boxed** [comment]
Ah, you don't have the iommi middleware installed. Hmm. I thought iommi would warn about that...

**Comment by boxed** [comment]
I assume the fix with getattr worked, so I released 1.1.2 with that fix. I also updated the readme to clear up the situation with the view.

**Comment by etamponi** [comment]
The page loads :) Now I have to understand how to use it... I'll open another issue! Thank you!
